apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pgbouncer.name" . }}-config
data:

  POSTGRESQL_HOST: {{ .Values.postgres_sql.POSTGRESQL_HOST }}
  #POSTGRESQL_USERNAME: {{ .Values.postgres_sql.POSTGRESQL_USERNAME }}
  POSTGRESQL_USERNAME: {{ .Values.users }}
  
  POSTGRESQL_DATABASE: {{ .Values.postgres_sql.POSTGRESQL_DATABASE }}
  POOL_MODE: {{ .Values.poolMode }}
