{{- if not .Values.existingUsersSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.name" . | nindent 4}}-secrets
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRESQL_PASSWORD: cG9zdGdyZXM=
{{- end -}}
